services:
  openmore:
    image: openmore:latest
    container_name: openmore
    environment:
      - DISPLAY=${DISPLAY}
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ../../../src:/openmore_ws/src
      - ~/.ros/log:/root/.ros/log
    stdin_open: true
    network: host
    tty: true
